name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USER: ${{secrets.DB_USER}}

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@v6
    - name: Install Dependencies
      run: |
        uv sync
    - name: Run Tests
      run: |
        cd recommendation_system && uv run pytest 
