name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Start MinIO Server
      uses: comfuture/minio-action@v1
      env:
        AWS_ACCESS_KEY_ID: minio-admin
        AWS_SECRET_ACCESS_KEY: minio-admin
        AWS_DEFAULT_REGION: us-east-1
      with:
        access_key: minio-admin
        secret_key: minio-admin
        port: 9000
        bucket_name: test-bucket
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@v6
    - name: Install Dependencies
      run: |
        uv sync
    - name: Run Tests
      run: |
        cd recommendation_system && uv run pytest 
